
# 🌍 Lab 4: การประมวลผลข้อมูลด้วย NumPy และ GeoPandas
## วิชา GE 234 Basic Programming for Geographers

### 🎯 **วัตถุประสงค์**
1. เข้าใจการใช้ **NumPy** สำหรับการประมวลผลข้อมูลทางภูมิศาสตร์ เช่น ข้อมูล Raster และพิกัด
2. ใช้ **GeoPandas** ในการจัดการและวิเคราะห์ข้อมูลเวกเตอร์ เช่น **Shapefile**
3. สามารถดำเนินการทางสถิติกับข้อมูลพิกัดและชั้นข้อมูลทางภูมิศาสตร์ได้
4. สามารถใช้ NumPy และ GeoPandas ร่วมกันเพื่อวิเคราะห์ข้อมูลได้

---

## 🔹 ตัวอย่างที่ 1: ใช้ NumPy คำนวณข้อมูล NDVI จากภาพ Raster

In [ ]:

import numpy as np

# สร้างข้อมูลตัวอย่างสำหรับภาพ NDVI (Normalized Difference Vegetation Index)
nir = np.array([[0.7, 0.8, 0.6], [0.9, 0.5, 0.3], [0.4, 0.7, 0.2]])
red = np.array([[0.3, 0.4, 0.2], [0.5, 0.3, 0.1], [0.2, 0.3, 0.1]])

# คำนวณค่า NDVI
ndvi = (nir - red) / (nir + red)

print("ค่า NDVI:")
print(ndvi)


## 🔹 ตัวอย่างที่ 2: ใช้ NumPy คำนวณค่าเฉลี่ยและค่ามากสุดของ NDVI

In [ ]:

print(f"ค่าเฉลี่ย NDVI: {np.mean(ndvi):.2f}")
print(f"ค่า NDVI สูงสุด: {np.max(ndvi):.2f}")
print(f"ค่า NDVI ต่ำสุด: {np.min(ndvi):.2f}")


## 🔹 ตัวอย่างที่ 3: ใช้ GeoPandas โหลดและวิเคราะห์ข้อมูล Shapefile

In [ ]:

import geopandas as gpd

# โหลดข้อมูลชั้นข้อมูลจังหวัดของประเทศไทย
gdf = gpd.read_file("https://data.opendevelopmentmekong.net/dataset/64ee3517-4e16-418f-81da-722c123ddacd/resource/ed6ff6ec-fbe6-43a5-99f1-e057c2796c33/download/th_province_boundary.shp")

# แสดงข้อมูล 5 แถวแรก
print(gdf.head())


## 🔹 ตัวอย่างที่ 4: คำนวณพื้นที่ของแต่ละจังหวัด

In [ ]:

# ตรวจสอบค่า CRS (Coordinate Reference System)
print(gdf.crs)

# คำนวณพื้นที่ของแต่ละจังหวัด (หน่วยเป็นตารางเมตร)
gdf["area_sqkm"] = gdf.geometry.area / 1e6

# แสดงพื้นที่จังหวัด 5 อันดับแรกที่ใหญ่ที่สุด
print(gdf.nlargest(5, "area_sqkm")[["PROV_NAME", "area_sqkm"]])


## 🔹 ตัวอย่างที่ 5: ใช้ GeoPandas ทำ Spatial Join

In [ ]:

# โหลดข้อมูลชั้นข้อมูลอำเภอ
gdf_districts = gpd.read_file("https://data.opendevelopmentmekong.net/dataset/ed8e818c-e1e3-4746-a7cd-6e437c078b9d/resource/9db5a579-2673-4e83-bf4f-bc7a83316c35/download/th_district_boundary.shp")

# ทำ Spatial Join ระหว่างอำเภอกับจังหวัด
gdf_joined = gpd.sjoin(gdf_districts, gdf, how="inner", predicate="within")

# แสดงตัวอย่างข้อมูลที่เชื่อมโยงกัน
print(gdf_joined.head())


# 📝 **กิจกรรมในแลป**

1. **แบบฝึกหัด 1**: ใช้ NumPy คำนวณค่า **Mean, Max, Min** ของค่า NDVI ในอาร์เรย์ที่สร้างขึ้นเอง
2. **แบบฝึกหัด 2**: ใช้ GeoPandas โหลด **Shapefile** ของจังหวัด และคำนวณพื้นที่ของแต่ละจังหวัด
3. **แบบฝึกหัด 3**: ใช้ GeoPandas ทำ **Spatial Join** ระหว่างข้อมูลจังหวัดและอำเภอ
4. **แบบฝึกหัด 4**: ใช้ NumPy และ GeoPandas ร่วมกันเพื่อหาข้อมูลจังหวัดที่มี NDVI เฉลี่ยสูงสุด

แบบฝึกหัด 1: ใช้ NumPy คำนวณค่า Mean, Max, Min ของค่า NDVI ในอาร์เรย์ที่สร้างขึ้นเอง

In [70]:
import numpy as np


nir_ex1 = np.array([[0.6, 0.7, 0.5],
                    [0.8, 0.6, 0.4],
                    [0.5, 0.8, 0.3]])

red_ex1 = np.array([[0.2, 0.3, 0.1],
                    [0.4, 0.2, 0.1],
                    [0.1, 0.2, 0.05]])

# คำนวณค่า NDVI
denominator = nir_ex1 + red_ex1
denominator[denominator == 0] = 1e-9 # ป้องกันการหารด้วยศูนย์
ndvi_ex1 = (nir_ex1 - red_ex1) / denominator

print("ค่า NDVI สำหรับแบบฝึกหัด 1:")
print(ndvi_ex1)


print(f"\nค่าเฉลี่ย NDVI: {np.mean(ndvi_ex1):.2f}")
print(f"ค่า NDVI สูงสุด: {np.max(ndvi_ex1):.2f}")
print(f"ค่า NDVI ต่ำสุด: {np.min(ndvi_ex1):.2f}")

ค่า NDVI สำหรับแบบฝึกหัด 1:
[[0.5        0.4        0.66666667]
 [0.33333333 0.5        0.6       ]
 [0.66666667 0.6        0.71428571]]

ค่าเฉลี่ย NDVI: 0.55
ค่า NDVI สูงสุด: 0.71
ค่า NDVI ต่ำสุด: 0.33

### **แบบฝึกหัด 2**: ใช้ GeoPandas โหลด Shapefile ของจังหวัด และคำนวณพื้นที่ของแต่ละจังหวัด

In [71]:
import geopandas as gpd
import os
import zipfile
import requests

url = "https://data.opendevelopmentmekong.net/th/dataset/8f3fa1b8-cb5c-48c8-9fd7-d3c213ea23db/resource/1559cee4-fedc-4330-be9c-d8cf3dd75015/download/tha_admbnda_adm1_rtsd_20190221.zip"
local_zip_path = "/tmp/tha_admbnda_adm1_rtsd_20190221.zip"
extracted_dir = "/tmp/tha_admbnda_adm1_rtsd_20190221"

os.makedirs(extracted_dir, exist_ok=True)

print(f"กำลังดาวน์โหลดไฟล์ Shapefile จาก: {url}")

try:
    response = requests.get(url, stream=True)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    with open(local_zip_path, 'wb') as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)
    print(f"ดาวน์โหลดไฟล์สำเร็จ: {local_zip_path}")
except requests.exceptions.RequestException as e:
    print(f"Error: ไม่สามารถดาวน์โหลดไฟล์จาก {url} ได้: {e}")
    raise


if os.path.exists(local_zip_path) and os.path.getsize(local_zip_path) > 0:
    try:
        with zipfile.ZipFile(local_zip_path, 'r') as zip_ref:
            zip_ref.extractall(extracted_dir)
        print(f"แตกไฟล์ไปที่: {extracted_dir}")

        shp_file_path = None
        for root, dirs, files in os.walk(extracted_dir):
            for file in files:
                if file.endswith(".shp"):
                    shp_file_path = os.path.join(root, file)
                    break
            if shp_file_path:
                break

        if shp_file_path:
            gdf_ex2 = gpd.read_file(shp_file_path)

            print("\nข้อมูล 5 แถวแรกของ Shapefile จังหวัดที่โหลดมา:")
            display(gdf_ex2.head())

            print(f"\nCRS ของข้อมูลจังหวัด: {gdf_ex2.crs}")

            # คำนวณพื้นที่ของแต่ละจังหวัด (หน่วยเป็นตารางกิโลเมตร)
            if gdf_ex2.crs.is_geographic: # ตรวจสอบว่าเป็น Geographic CRS (ละติจูด/ลองจิจูด)
                print("\nCRS เป็น Geographic CRS กำลังแปลงเป็น Projected CRS เพื่อคำนวณพื้นที่ที่แม่นยำ...")
                if not gdf_ex2.geometry.is_empty.all():
                    # WGS 84 / UTM zone 47N (EPSG:32647) is suitable for a large part of Thailand
                    gdf_ex2_proj = gdf_ex2.to_crs("EPSG:32647")
                    gdf_ex2["area_sqkm_ex2"] = gdf_ex2_proj.geometry.area / 1e6
                else:
                    print("Warning: Geometry is empty, cannot calculate area.")
                    gdf_ex2["area_sqkm_ex2"] = 0
            else:
                gdf_ex2["area_sqkm_ex2"] = gdf_ex2.geometry.area / 1e6

            print("\nจังหวัด 5 อันดับแรกที่มีพื้นที่มากที่สุด (จากแบบฝึกหัด 2):")
            # Dynamically find a suitable province name column
            province_name_col = None
            for col in ['PROV_NAME', 'ADM1_EN', 'NAME_1']:
                if col in gdf_ex2.columns:
                    province_name_col = col
                    break

            if province_name_col:
                display(gdf_ex2.nlargest(5, "area_sqkm_ex2")[[province_name_col, "area_sqkm_ex2"]])
            else:
                display(gdf_ex2.nlargest(5, "area_sqkm_ex2")[["area_sqkm_ex2"]])
        else:
            print(f"Error: ไม่พบไฟล์ .shp ภายใน {extracted_dir}")

    except zipfile.BadZipFile:
        print(f"Error: ไฟล์ที่ดาวน์โหลดมาไม่ใช่ไฟล์ Zip ที่ถูกต้อง: {local_zip_path}")
    except Exception as e:
        print(f"เกิดข้อผิดพลาดระหว่างแตกไฟล์หรืออ่าน Shapefile: {e}")
else:
    print(f"Error: ไม่สามารถดาวน์โหลดไฟล์จาก {url} ได้สำเร็จ หรือไฟล์ที่ดาวน์โหลดมาว่างเปล่า")

กำลังดาวน์โหลดไฟล์ Shapefile จาก: https://data.opendevelopmentmekong.net/th/dataset/8f3fa1b8-cb5c-48c8-9fd7-d3c213ea23db/resource/1559cee4-fedc-4330-be9c-d8cf3dd75015/download/tha_admbnda_adm1_rtsd_20190221.zip
ดาวน์โหลดไฟล์สำเร็จ: /tmp/tha_admbnda_adm1_rtsd_20190221.zip
แตกไฟล์ไปที่: /tmp/tha_admbnda_adm1_rtsd_20190221

ข้อมูล 5 แถวแรกของ Shapefile จังหวัดที่โหลดมา:

,Shape_Leng,Shape_Area,ADM1_EN,ADM1_TH,ADM1_PCODE,ADM1_REF,ADM1ALT1EN,ADM1ALT2EN,ADM1ALT1TH,ADM1ALT2TH,ADM0_EN,ADM0_TH,ADM0_PCODE,date,validOn,validTo,geometry
0,3.927244,0.275313,Amnat Charoen,อำนาจเจริญ,TH37,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((104.95982 16.28359, 104.95986 16.283..."
1,1.739908,0.079210,Ang Thong,อ่างทอง,TH15,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((100.33319 14.79853, 100.33341 14.798..."
2,2.417227,0.131339,Bangkok,กรุงเทพมหานคร,TH10,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((100.61389 13.95462, 100.61428 13.954..."
3,4.414998,0.340784,Bueng Kan,บึงกาฬ,TH38,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((103.40497 18.44898, 103.40619 18.448..."
4,8.701860,0.844537,Buri Ram,บุรีรัมย์,TH31,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((102.93029 15.79514, 102.93029 15.795..."

CRS ของข้อมูลจังหวัด: EPSG:4326

CRS เป็น Geographic CRS กำลังแปลงเป็น Projected CRS เพื่อคำนวณพื้นที่ที่แม่นยำ...

จังหวัด 5 อันดับแรกที่มีพื้นที่มากที่สุด (จากแบบฝึกหัด 2):

              ADM1_EN  area_sqkm_ex2
9          Chiang Mai   22159.519971
28  Nakhon Ratchasima   20750.869676
15       Kanchanaburi   19436.356316
68                Tak   17266.546740
71   Ubon Ratchathani   15636.863442

แบบฝึกหัด 3: ใช้ GeoPandas ทำ Spatial Join ระหว่างข้อมูลจังหวัดและอำเภอ

In [72]:
import geopandas as gpd
from IPython.display import display

gdf = gpd.read_file("https://data.opendevelopmentmekong.net/dataset/6f054351-bf2c-422e-8deb-0a511d63a315/resource/84b5e1ef-31f7-4760-bc3a-ac58269acc87/download/diaphanhuyen.zip")
print("ข้อมูลดิบ (gdf.head()):")
display(gdf.head())

gdf_districts = gpd.read_file("https://data.opendevelopmentmekong.net/dataset/6f054351-bf2c-422e-8deb-0a511d63a315/resource/84b5e1ef-31f7-4760-bc3a-ac58269acc87/download/diaphanhuyen.zip")

gdf_joined = gpd.sjoin(gdf_districts, gdf, how="inner", predicate="within")

print("ข้อมูลที่ผ่าน Spatial Join (gdf_joined ทั้งหมด):")
display(gdf_joined)

ข้อมูลดิบ (gdf.head()):

,OBJECTID,f_code,Ten_Tinh,Ten_Huyen,Dan_So,Nam_TK,Code_vung,geometry
0,1,AD02,Cà Mau,Nam Căn,66229,2009,96971,"POLYGON ((105.05492 8.85322, 105.05819 8.85155..."
1,2,AD02,Cà Mau,Dam Doi,182028,2009,96970,"POLYGON ((105.16041 9.09551, 105.16228 9.09309..."
2,3,AD02,Cà Mau,Cái Nước,137396,2009,96969,"POLYGON ((105.08692 9.13987, 105.08773 9.13954..."
3,4,AD02,Bạc Liêu,Đông Hải,143590,2009,95960,"POLYGON ((105.55273 9.23437, 105.56841 9.17901..."
4,5,AD02,Cà Mau,TP. Cà Mau,216196,2009,96964,"POLYGON ((105.1723 9.26629, 105.17518 9.26575,..."

ข้อมูลที่ผ่าน Spatial Join (gdf_joined ทั้งหมด):

,OBJECTID_left,f_code_left,Ten_Tinh_left,Ten_Huyen_left,Dan_So_left,Nam_TK_left,Code_vung_left,geometry,index_right,OBJECTID_right,f_code_right,Ten_Tinh_right,Ten_Huyen_right,Dan_So_right,Nam_TK_right,Code_vung_right
0,1,AD02,Cà Mau,Nam Căn,66229,2009,96971,"POLYGON ((105.05492 8.85322, 105.05819 8.85155...",0,1,AD02,Cà Mau,Nam Căn,66229,2009,96971
1,2,AD02,Cà Mau,Dam Doi,182028,2009,96970,"POLYGON ((105.16041 9.09551, 105.16228 9.09309...",1,2,AD02,Cà Mau,Dam Doi,182028,2009,96970
2,3,AD02,Cà Mau,Cái Nước,137396,2009,96969,"POLYGON ((105.08692 9.13987, 105.08773 9.13954...",2,3,AD02,Cà Mau,Cái Nước,137396,2009,96969
3,4,AD02,Bạc Liêu,Đông Hải,143590,2009,95960,"POLYGON ((105.55273 9.23437, 105.56841 9.17901...",3,4,AD02,Bạc Liêu,Đông Hải,143590,2009,95960
4,5,AD02,Cà Mau,TP. Cà Mau,216196,2009,96964,"POLYGON ((105.1723 9.26629, 105.17518 9.26575,...",4,5,AD02,Cà Mau,TP. Cà Mau,216196,2009,96964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1556,1557,AD02,Kiên Giang,Ha Tien,0,2009,91900,"POLYGON ((104.33437 10.40593, 104.33481 10.405...",1556,1557,AD02,Kiên Giang,Ha Tien,0,2009,91900
1557,1558,AD02,Kiên Giang,Ha Tien,0,2009,91900,"POLYGON ((104.32954 10.4084, 104.32982 10.4083...",1557,1558,AD02,Kiên Giang,Ha Tien,0,2009,91900
1558,1559,AD02,Kiên Giang,Ha Tien,0,2009,91900,"POLYGON ((104.34276 10.42838, 104.34308 10.427...",1558,1559,AD02,Kiên Giang,Ha Tien,0,2009,91900
1559,1560,AD02,Kiên Giang,Ha Tien,0,2009,91900,"POLYGON ((104.32564 10.44309, 104.32986 10.441...",1559,1560,AD02,Kiên Giang,Ha Tien,0,2009,91900
1560,1561,AD02,Kiên Giang,Ha Tien,0,2009,91900,"POLYGON ((104.33165 10.455, 104.33193 10.45493...",1560,1561,AD02,Kiên Giang,Ha Tien,0,2009,91900

แบบฝึกหัด 4: ใช้ NumPy และ GeoPandas ร่วมกันเพื่อหาข้อมูลจังหวัดที่มี NDVI เฉลี่ยสูงสุด

In [73]:
import numpy as np
import geopandas as gpd
from IPython.display import display

# ตรวจสอบว่า gdf_ex2 มีอยู่จริงหรือไม่ (ควรจะถูกสร้างในเซลล์ e6ab145c)
# ถ้าไม่มี ให้รันเซลล์ e6ab145c ก่อน
if 'gdf_ex2' not in locals():
    print("Warning: gdf_ex2 is not found. Please run Exercise 2 cell (e6ab145c) first.")
    # As a fallback for demonstration, load a simple version if gdf_ex2 is truly missing
    # In a real scenario, the user would need to run the previous cell.
    try:
        # Attempt to load the same file used in Ex2 if gdf_ex2 is not in locals
        extracted_dir = "/tmp/tha_admbnda_adm1_rtsd_20190221"
        shp_file_path = None
        for root, dirs, files in os.walk(extracted_dir):
            for file in files:
                if file.endswith(".shp"):
                    shp_file_path = os.path.join(root, file)
                    break
            if shp_file_path:
                break
        if shp_file_path:
            gdf_ex2 = gpd.read_file(shp_file_path)
            # Simulate area calculation for consistency if reloaded
            if gdf_ex2.crs.is_geographic:
                gdf_ex2_proj = gdf_ex2.to_crs("EPSG:32647")
                gdf_ex2["area_sqkm_ex2"] = gdf_ex2_proj.geometry.area / 1e6
            else:
                gdf_ex2["area_sqkm_ex2"] = gdf_ex2.geometry.area / 1e6
        else:
            raise FileNotFoundError(f"Cannot find .shp file in {extracted_dir}")
    except Exception as e:
        print(f"Error reloading gdf_ex2 for fallback: {e}")
        # Create a dummy DataFrame if all else fails to allow code execution
        data = {'PROV_NAME': ['Province A', 'Province B', 'Province C'],
                'geometry': [None, None, None],
                'area_sqkm_ex2': [1000, 2000, 1500]}
        gdf_ex2 = gpd.GeoDataFrame(data)


# --- Simulate NDVI data for each province using NumPy ---
# สร้างอาร์เรย์ของค่า NDVI สุ่มหนึ่งค่าสำหรับแต่ละจังหวัดใน gdf_ex2
# ค่า NDVI มักจะอยู่ระหว่าง -1 ถึง 1. เราจะจำลองค่าที่สมจริง (เช่น 0.1 ถึง 0.9 สำหรับพื้นที่พืชพรรณ)
np.random.seed(42) # เพื่อให้ผลลัพธ์สามารถทำซ้ำได้
simulated_ndvi_values = np.random.uniform(0.1, 0.9, size=len(gdf_ex2))

# เพิ่มค่า NDVI จำลองเป็นคอลัมน์ใหม่ใน DataFrame gdf_ex2
gdf_ex2['avg_ndvi'] = simulated_ndvi_values

print("ข้อมูลจังหวัดพร้อมค่า NDVI เฉลี่ยจำลอง (5 แถวแรก):")
display(gdf_ex2.head())

# --- ค้นหาจังหวัดที่มีค่า NDVI เฉลี่ยสูงสุดโดยใช้ GeoPandas/Pandas ---
# ใช้ชื่อคอลัมน์จังหวัดที่ระบุจากแบบฝึกหัดที่ 2, หรือใช้ค่าเริ่มต้นเป็น 'ADM1_EN'
province_name_col_ex4 = None
for col_name in ['PROV_NAME', 'ADM1_EN', 'NAME_1']:
    if col_name in gdf_ex2.columns:
        province_name_col_ex4 = col_name
        break

if province_name_col_ex4:
    province_with_highest_ndvi = gdf_ex2.loc[gdf_ex2['avg_ndvi'].idxmax()]

    print(f"\nจังหวัดที่มีค่า NDVI เฉลี่ยสูงสุดคือ:")
    print(f"ชื่อจังหวัด: {province_with_highest_ndvi[province_name_col_ex4]}")
    print(f"ค่า NDVI เฉลี่ย: {province_with_highest_ndvi['avg_ndvi']:.2f}")

    # แสดงแถวข้อมูลทั้งหมดเพื่อบริบท
    display(province_with_highest_ndvi[[province_name_col_ex4, 'avg_ndvi', 'area_sqkm_ex2']].to_frame().T)
else:
    print("ไม่พบคอลัมน์ชื่อจังหวัดที่เหมาะสมใน DataFrame.")

ข้อมูลจังหวัดพร้อมค่า NDVI เฉลี่ยจำลอง (5 แถวแรก):

,Shape_Leng,Shape_Area,ADM1_EN,ADM1_TH,ADM1_PCODE,ADM1_REF,ADM1ALT1EN,ADM1ALT2EN,ADM1ALT1TH,ADM1ALT2TH,ADM0_EN,ADM0_TH,ADM0_PCODE,date,validOn,validTo,geometry,area_sqkm_ex2,avg_ndvi
0,3.927244,0.275313,Amnat Charoen,อำนาจเจริญ,TH37,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((104.95982 16.28359, 104.95986 16.283...",3290.635392,0.399632
1,1.739908,0.079210,Ang Thong,อ่างทอง,TH15,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((100.33319 14.79853, 100.33341 14.798...",943.956101,0.860571
2,2.417227,0.131339,Bangkok,กรุงเทพมหานคร,TH10,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((100.61389 13.95462, 100.61428 13.954...",1571.323599,0.685595
3,4.414998,0.340784,Bueng Kan,บึงกาฬ,TH38,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((103.40497 18.44898, 103.40619 18.448...",4012.682238,0.578927
4,8.701860,0.844537,Buri Ram,บุรีรัมย์,TH31,None,None,None,None,None,Thailand,ประเทศไทย,TH,2019-02-18,2019-02-21,NaT,"POLYGON ((102.93029 15.79514, 102.93029 15.795...",10095.554993,0.224815

จังหวัดที่มีค่า NDVI เฉลี่ยสูงสุดคือ:
ชื่อจังหวัด: Trang
ค่า NDVI เฉลี่ย: 0.89

   ADM1_EN avg_ndvi area_sqkm_ex2
69   Trang  0.88951   4706.513504